config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'home#index'
    post '/', to: 'home#create'
  end

  root 'home#index'
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

module Admin
  class HomeController < ApplicationController
    def index
      last_manual_currency = CurrencyCacheQuery.call(cache_name: 'last_manual_currency')
      @currency, @time = last_manual_currency.values if last_manual_currency.present?
    end

    def create
      SetCurrencyManual.call(value: currency_params[:value], time: currency_params[:time])
      redirect_to admin_root_path
    end

    private

    def currency_params
      params.permit(:value, :time)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @currency_data = CurrencyCacheQuery.call
  end
end

app/helpers/admin/home_helper.rb
# frozen_string_literal: true

module Admin
  module HomeHelper
    def manual_currency_already_on?
      return if @time.blank?

      Time.zone.parse(@time) > Time.current
    end

    def default_time
      return if @time.blank?

      Time.zone.parse(@time).strftime('%Y-%m-%dT%H:%M')
    end

    def minimum_acceptable_time
      1.minute.from_now.strftime('%Y-%m-%dT%H:%M')
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/home/index.html.slim
h1 Set currency manual
= form_tag(admin_path) do
  .form-group.col-md-3
    = label_tag :value
    = number_field_tag :value, @currency, class: 'form-control', min: 1
    = label_tag :time
    = datetime_local_field_tag :time, default_time, min: minimum_acceptable_time, class: 'form-control'
  = submit_tag 'Set', class: 'btn btn-primary', disabled: manual_currency_already_on?

app/views/home/index.html.slim
.row
  .col-md
    h1
      em.text-success.display-1 1$ &#61
      em.text-success.display-1#currency= " #{@currency_data[:value]}"
      em.text-success.display-1 ₽
.row
  .col-md
    p
      em.small.text-secondary Updated at
      em.small.text-secondary#updated_at= " #{@currency_data[:time]}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title ShowMeDollar
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container-fluid
      = yield